version: "3"
services:
  jenkins:
    build: .
    ports:
      - 8080:8080
    volumes:
      - /home/maron8676/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
